name: Front-end

on: [push, pull_request]

jobs:
  django:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build frontend
      run: make regenerate_frontend
    - name: Show git status
      run: git status
    - name: Require rebuild content
      run: >
        git diff-index --quiet HEAD -- "poradnia/static/" || (
          echo "Pending changes in the front-end have been detected.";
          echo "Use 'make regenerate_frontend' to regenerate front-end and commit changes.";
          exit 1;
        )